---
name: Deploy CV to GitHub Pages
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Guix cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/guix
          key: guix-cache-${{ github.sha }}
          restore-keys: |
            guix-cache-
      - name: Install Guix
        uses: PromyLOPH/guix-install-action@v1
      - name: Build CV
        run: guix build --root=out --fallback -f guix.scm
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: out/

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
